### ISSUE TITLE
Dungeon 1 boss: eggs and chocobos stuck in the iron ball

### ISSUE THREAD

**Issue by christopho** [solarus-games/zelda-xd2-mercuris-chess#4]

**Comment by Diarandor** [comment]
-I confirm that this happens. It happened to me that after throwing the ball, it fell exactly in the spawning point of chocobos, so they appeared stuck in the ball (probably the same problem you found).
 Also, the hero is sometimes stuck in the ball (once I was not able to lift it,with the hero stuck, which forced to reset the game). I suggest to make the cannon ball traversable to avoid some of these problems, and remove it when the last column has been destroyed since it is not necessary anymore.
-Another problem I've found is that sometimes the ball does not make a parabolic trajectory; and sometimes the ball gets stuck on the wall and cannot be lifted again (throw it towards a wall in the "up" direction to reproduce this).
-Also, jumping into the water while carrying the cannon ball is not recommended, since the ball will fall into the water and cannot be lifted again (it should be destroyed, I think).
-If you need to improve the parabolic trajectory for throwing it, just take a look to my old sript, or ask me directly to write the function.
